#!/usr/bin/python

import sys
import os
from os import path, environ
import subprocess

examples_dir = "../examples/"

for files in os.listdir(examples_dir):
    if files.endswith(".cl"):
        os.system("./lexer ../examples/io.cl > mylexer.out");
        os.system("./coolc -k ../examples/io.cl")
        os.system("diff lexer.out mylexer.out >> test.log");
        print files

