
class StringConstTest {

    test5 : String <- "this string has null \0";
    test6 : String <- "testing escape: \a \c \b \\";
    test7 : String <- "testing tab: \t. After tab.";
    test8 : String <- "length exceeds max                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               ";
    test8 : String <- "length doesn't exceed max                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       ";
}
