#!/usr/bin/python

import sys
import os
from os import path, environ

examples_dir = "../examples/"
#examples_dir = "../"
os.system("echo (*begin testing*) > test_good.log");

for files in os.listdir(examples_dir):
    if files.endswith(".cl"):
        os.system("./lexer "+examples_dir+files+" | ./parser > myparser.out");
        os.system("./coolc -k "+examples_dir+files);
        os.system("echo "+files+" >> test_good.log");
        os.system("diff myparser.out parser.out >> test_good.log");
        print files

os.system("echo (*begin testing*) > test_bad.log");
for files in os.listdir(examples_dir):
    if files.endswith(".cl"):
        os.system("./lexer "+examples_dir+files+" | ./parser 2> myparser.out");
        os.system("./coolc -k "+examples_dir+files+" 2> parser.out");
        os.system("echo "+files+" >> test_bad.log");
        os.system("diff myparser.out parser.out >> test_bad.log");
        print files
